### ISSUE TITLE
0.14 release

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#947]
~~- [ ] revert breaking changes to AssemblyReferences in #953 (PR raised https://github.com/scriptcs/scriptcs/pull/969) (@adamralph)~~
- [x] fix regression in #964 (@filipw + @adamralph)
- [x] revert breaking ScriptExecutor change in #909 (PR https://github.com/scriptcs/scriptcs/pull/981) - [x] ensure all 0.14 issues are attached to the milestone and labelled appropriately (@adamralph)
(@adamralph + @glennblock)
- [x] bump version number (PR https://github.com/scriptcs/scriptcs/pull/95) (@adamralph + @khellang)
- [x] draft GitHub release *with tag on* ***master*** (@adamralph)
- [x] smoke tests
  - [x] script packs (@adamralph)
    - [x] Bau
    - [x] Nancy
  - [x] modules
    - [x] gist
    - [x] CSharp (@filipw)
    - [x] VisualBasic (@filipw)
  - [x] hosts (@adamralph)
    - [x] ConfigR
- [x] ensure PR for blog post regarding #909 is ready to be merged (PR https://github.com/scriptcs/scriptcs.github.com/pull/2) (@paulbouwer + @glennblock)
- [x] raise and merge PR from dev to master
- [x] confirm packages have been uploaded to Chocolatey
- [x] publish GitHub release
- [x] merge blog post PR
- [x] announce on official Twitter account
- [x] raise PR for version bump

**Comment by glennblock** [comment]
Marked as hold based on breaking change related to module loading. @filipw will fix

**Comment by filipw** [comment]
#968

**Comment by glennblock** [comment]
Also added module loading tests as a prereq for the release

**Comment by filipw** [comment]
:shipit:

**Comment by filipw** [comment]
both of the new engine modules work with this codebase, if that counts for a smoke test

**Comment by adamralph** [comment]
Ah, indeed it does!
